### ISSUE TITLE
Is it supposed to run some backend ? 

### ISSUE THREAD

**Issue by alexbnk** [bohap/generator-angular-jwt-starter#1]
i got this on registration attempt:

Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by bohap** [comment]
Hi, yes it need to have some backend, this is only a front end generator.
